baseURL = "https://iohana31.github.io/"
languageCode = "en-us"
title = "Welcome"
theme = "hugo-resume"

[params]
    firstName = "Iohana"
    lastName = "D"
    address = "Rollinsford, NH"
    phone = "1-555-555-1234"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/cat.jpg"
    email = "email@domain.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
